### ISSUE TITLE
conda-forge package

### ISSUE THREAD

**Issue by hoechenberger** [raphaelvallat/antropy#18]
Hello, I've added `antropy` to `conda-forge`; please let me know if you'd like to be added as a co-maintainer for the respective feedstock. It could also make sense to amend the installation instructions, WDYT?

**Comment by raphaelvallat** [comment]
Hi @hoechenberger,

Yay, thank you! And thanks for everything that you're doing for the Python open-science community :) Please do add me as a co-maintainer. 

Agree for the installation instructions, so `conda install antropy` should work?

**Comment by hoechenberger** [comment]
Hey @raphaelvallat,

thanks!! 😍 I can only say the same about your efforts 😄 

I've added you as a feedstock maintainer.

The recommended way to install the package from `conda-forge` is documented here:

https://github.com/conda-forge/antropy-feedstock#installing-antropy

> Installing antropy from the conda-forge channel can be achieved by adding conda-forge to your channels with:
> 
> ```
> conda config --add channels conda-forge
> conda config --set channel_priority strict
> ```
> Once the conda-forge channel has been enabled, antropy can be installed with conda:
> 
> ```
> conda install antropy
> ```
> or with mamba:
> 
> ```
> mamba install antropy
> ```

**Comment by raphaelvallat** [comment]
Thanks — added in https://github.com/raphaelvallat/antropy/pull/19
