### ISSUE TITLE
Allow users to pass signal in frequency domain in spectral entropy

### ISSUE THREAD

**Issue by raphaelvallat** [raphaelvallat/antropy#2]
Currently, [antropy.spectral_entropy](https://raphaelvallat.com/antropy/build/html/generated/antropy.spectral_entropy.html#antropy.spectral_entropy) only allows ``x`` to be in time-domain. We should add ``freqs=None`` and ``psd=None`` as possible input if users want to calculate the spectral entropy of a pre-computed power spectrum. We should also add an example of how to calculate the spectral entropy from a multitaper power spectrum.

**Comment by LMBooth** [comment]
You could pull the multi-taper power spectrum function from MNE?
