### ISSUE TITLE
Errors in sample_entropy and higuchi_fd on a small vector

### ISSUE THREAD

**Issue by fingoldo** [raphaelvallat/antropy#24]
Hi, is this supposed to be?

```
import antropy as ant

print(ant.sample_entropy([-1, 2, 1, 3, 3]))
```

> C:\ProgramData\Anaconda3\lib\site-packages\antropy\entropy.py in sample_entropy(x, order, metric)
>     663     x = np.asarray(x, dtype=np.float64)
>     664     if metric == "chebyshev" and x.size < 5000:
> --> 665         return _numba_sampen(x, order=order, r=(0.2 * x.std(ddof=0)))
>     666     else:
>     667         phi = _app_samp_entropy(x, order=order, metric=metric, approximate=False)
> 
> IndexError: getitem out of range

`print(ant.higuchi_fd(x))
`

> C:\ProgramData\Anaconda3\lib\site-packages\antropy\fractal.py in higuchi_fd(x, kmax)
>     297     x = np.asarray(x, dtype=np.float64)
>     298     kmax = int(kmax)
> --> 299     return _higuchi_fd(x, kmax)
>     300 
>     301 
> 
> ZeroDivisionError: division by zero

**Comment by raphaelvallat** [comment]
Hi,

I think that it doesn't really make sense to calculate the entropy or fractal dimension on such small arrays. That said, I haven't formally tested what should be the minimum sample size for these functions. It would be helpful to add a more explicit error message when the sample size is too low.

Thanks,
Raphael

**Comment by FirefoxMetzger** [comment]
I just ran into this as well when benchmarking the old and the new kernel. The old kernel works fine from 6 samples onwards for `order=2`. My guess is that the old kernel accessed the samples in blocks of a certain length (perhaps 2*(order+1)?) and thus needs at least one window/block worth of data to operate.

The new kernel doesn't have this limitation and will work happily with any array length. That said, @raphaelvallat comment still stands: sample_entropy is not reliable on small sample sizes so results should be taken with a grain of salt.

**Comment by raphaelvallat** [comment]
Should be fixed in https://github.com/raphaelvallat/antropy/releases/tag/v0.1.6 since we are now using the new kernel
