### ISSUE TITLE
Fix KDTree all_metrics

### ISSUE THREAD

**Issue by fingoldo** [raphaelvallat/antropy#28]
Hi, I noticed that in new sklearn they have probably changed 

KDTree.valid_metrics from a list to a method, and antropy does not work with it anymore.
Suggesting to add line 376 in antropy.py to resolve the issue:

`if type(_all_metrics).__name__=='builtin_function_or_method': _all_metrics=_all_metrics()`

**Comment by lucianolorenti** [comment]
I think they regressed the change in 1.3.1

https://github.com/scikit-learn/scikit-learn/pull/26754

**Comment by raphaelvallat** [comment]
Released in https://github.com/raphaelvallat/antropy/releases/tag/v0.1.6
